### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by mervin-john** [nickperkinslondon/angular-bootstrap-nav-tree#126]
Can i get this tree support in Angular 7?

**Comment by daerogami** [comment]
Hi @mervin-john, I am currently working though old PRs and issues. I fully intend to investigate adding modern angular support but it will be a while as the coffee script file will need to be converted to typescript and that is after all the necessary tests and CI is implemented to ensure backwards compatibility does not break.

**Comment by daerogami** [comment]
duplicates #110
