### ISSUE TITLE
expand-level doesn't work on scope change

### ISSUE THREAD

**Issue by atiertant** [nickperkinslondon/angular-bootstrap-nav-tree#16]
hello,

like in you sample : http://nickperkinslondon.github.io/angular-bootstrap-nav-tree/test/bs3_ng120_test_page.html
when clicking button,the expand level is not applyed.

thanks for your work

**Comment by davaus** [comment]
I tried the "on_treeData_change" modification used above, but it stopped any further expansion below the initial one. I found the following change to the first few lines of "add_branch_to_list" worked well.
` 
add_branch_to_list = function(level, branch, visible) {

              var child, child_visible, tree_icon, _i, _len, _ref, _results;

              if (branch.expanded == null) {

                  branch.expanded = level <= expand_level;  

              }`

**Comment by daerogami** [comment]
I cannot recreate this issue. Closing due to age.

If this is still a problem, reopen and provide a more thorough description.
