### ISSUE TITLE
add to nuget

### ISSUE THREAD

**Issue by bbodenmiller** [nickperkinslondon/angular-bootstrap-nav-tree#31]
Similar to your [Bower support](https://github.com/nickperkinslondon/angular-bootstrap-nav-tree/issues/11) would be great to add this to [NuGet](http://www.nuget.org/).

**Comment by poloagustin** [comment]
Seems that this issue has a hole year already open. I was thinking about creating the package myself :)

**Comment by daerogami** [comment]
The leading paradigm now is to use npm from Visual Studio. (likely wasn't when this issue was opened)

If there is still some reason this is untenable, feel free to reopen.
