### ISSUE TITLE
Tree loses indentation when changing the model

### ISSUE THREAD

**Issue by SubatomicHero** [nickperkinslondon/angular-bootstrap-nav-tree#37]
Hi there,

When I changed the treeData going into the directive (new tree maybe or reloading an old tree) the "structure" is lost. All the nodes and leaves are aligned in indentation.

Expanding/collapsing still works, but the indentation is no longer applied.

Thanks,

Martin

**Comment by daerogami** [comment]
I believe this is related to initialization that occurs on the tree object initially provided to the directive. If that object is being overwritten, that may explain the issue. It not only blows away that initial data, but overwriting an object being passed to a directive can break its binding.

If I have misunderstood something and this is still an issue, feel free to reopen.
