### ISSUE TITLE
Tag commits so I can use bower.

### ISSUE THREAD

**Issue by stefankendall** [nickperkinslondon/angular-bootstrap-nav-tree#46]
Right now, I can only use master in bower. I'd like to be able to lock to versions.

Could you tag a release so I can fix to a version?

**Comment by lampapetrol** [comment]
@tisto : you can already freeze the version by providing a git commit hash : http://bower.io/docs/api/#install / https://github.com/bower/bower/pull/441

**Comment by jamesward** [comment]
+1 Please tag a release.

**Comment by daerogami** [comment]
@jamesward Probably long overdue, but I have created a tag/release on the latest commit consistent with the version in package.json. While that version info likely hasn't been kept up-to-date, this should at least help set a static reference from the repo metadata for those that need it.
