### ISSUE TITLE
can we add sort functionality to the tree view ?

### ISSUE THREAD

**Issue by vsonone** [nickperkinslondon/angular-bootstrap-nav-tree#54]
How difficult will it be to add sort and filter feature to this tree ?

**Comment by benoror** [comment]
Filtering issue duplicated at: https://github.com/nickperkinslondon/angular-bootstrap-nav-tree/issues/47

**Comment by benoror** [comment]
I would also like to filter elements from the nav-tree using a search input, any idea?

**Comment by justjoheinz** [comment]
+1

**Comment by trondhuso** [comment]
+1 also

**Comment by daerogami** [comment]
As previously mentioned, this is a duplicate of #47
