### ISSUE TITLE
Selecting same branch twice

### ISSUE THREAD

**Issue by ncd76** [nickperkinslondon/angular-bootstrap-nav-tree#60]
If I have a branch without children and click it twice the $scope.events_tree_handler only fires once, you need to click on another branch and back to the first t get it to fire again.

I've hacked abn_tree_directive.js to get this to work:

scope.user_clicks_branch = function(branch) {
            if (branch !== selected_branch) {
              var ret = select_branch(branch);
              selected_branch = null;
              return ret;
            }
};

**Comment by daerogami** [comment]
This is expected behavior as the handler is for on-select which is semantically distinct from on-click. The current branch can be retrieved via `tree.get_selected_branch()`.

Reopen if this is still a desired feature and will discuss potential implementations.
