### ISSUE TITLE
Set initial selection from JavaScript or controller

### ISSUE THREAD

**Issue by dlwhiteman** [nickperkinslondon/angular-bootstrap-nav-tree#64]
Is it possible to programmatically set the initial selection of the nav tree?  When the nav tree is clicked, I am setting a variable in my controller's scope to save the current node label, and then setting location.href to switch to a new page.  When the page reloads, the tree forgets its previous selection.  Is it possible for me to set the initial tree selection from my controller, or the ready function, to a specific branch label?

**Comment by MicahFulton** [comment]
Wouldn't it make more sense in this case to call: 
```
tree.select_branch(<branch>)
```
In your controller in this case?

**Comment by vikasgupta1986** [comment]
MicahFulton,

What is the 'tree' you're referring to?

**Comment by thienhung1989** [comment]
```html
<abn-tree 
    tree-control      = "my_tree"  
></abn-tree>```

In controller:
```js
     $scope.my_tree = tree = {};
     var _branch = tree.select_first_branch(); // 
     tree.select_branch(_branch)
```

**Comment by daerogami** [comment]
The selected branch is persisted in the tree, if your tree is getting reset from a location change instead of a routing change, you will need to write the infrastructure to re-select it.

Suggestions preceding this comment appear sufficient.
