### ISSUE TITLE
This doesn't work in IE

### ISSUE THREAD

**Issue by swami-108** [nickperkinslondon/angular-bootstrap-nav-tree#71]
This doesn't work in IE. Even the example page does not work in IE 9.  Will IE be supported in the future?

**Comment by Andrewpk** [comment]
Works great in IE 11. IE 9 was released in 2011 and IE 11 is supported on Windows 7 so you could always upgrade or use a more compliant browser.

**Comment by daerogami** [comment]
Anything under IE11 will not be explicitly supported.
