### ISSUE TITLE
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed.

### ISSUE THREAD

**Issue by campa** [nickperkinslondon/angular-bootstrap-nav-tree#74]
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: row in tree_rows | filter:{visible:true} track by row.branch.uid, Duplicate key: undefined, Duplicate value: {"level":2,"branch":{"label":"Less","children":[],"expanded":false,"classes":["leaf"]},"label":"Less","classes":"<<already seen>>","tree_icon":"icon-file  glyphicon glyphicon-file  fa fa-file","visible":true}
http://errors.angularjs.org/1.3.11/ngRepeat/dupes?

**Comment by benoror** [comment]
It's caused when using an array of string(s), or an empty one, for children:

    {"label":"Less","children":[]}
    // or
    {"label":"Less","children":['any','thing']}

should be:

    {"label":"Less","children":[{label: 'any'},{label: 'thing'}]}

**Comment by windy** [comment]
@benoror @campa I have the same problem, but it's sovled like this.

But I copy the tree data from the example page: http://nickperkinslondon.github.io/angular-bootstrap-nav-tree/test/bs3_ng120_test_page.html

The example page has the same error, I think it should be fixed.

**Comment by benoror** [comment]
I don't see it in my console windy

**Comment by zschiffelbein** [comment]
I agree that this should be fixed in the example

**Comment by ghost** [comment]
Example code is still toxic and hasn't been updated.
Use this instead:
`$scope.my_data =
[{
        'label' : 'Parent',
        'children' :
            [
                { 'label': 'Child1' },
                { 'label': 'Child2' },
                { 'label': 'Child3' }
            ]
    }];`
