### ISSUE TITLE
catch expand/collapse vs select

### ISSUE THREAD

**Issue by trondhuso** [nickperkinslondon/angular-bootstrap-nav-tree#94]
First of:
Nick: Thanks for creating such a great directive!

When I am using this directive I call some APIs based on user actions. Just that I don't want to call these APIs when someone is just expanding or collapsing the node. Is there a way to distinguish between selecting and expanding/collapsing?

**Comment by guicoma** [comment]
There are also people with the same interest in another issue #66

**Comment by daerogami** [comment]
Duplicate of #66
